#!/bin/bash
bg="asd"
bg=$(sxiv $(find ~/pics/background/ |shuf) -f -o -t)
if ! [ -z "$bg" ]; then
	echo $bg  > ~/.sh/defaultwallpaper
	~/.sh/wallpaper
	.sh/colourdunst
	sleep 1
	dunstify -r 80085 -i "$bg" "Background changed"
fi
exit
