#!/bin/bash
BRIGHTNESS=$(light)
DISKUSAGE=$(df -h|awk '$1 == "/dev/sda1" {print "/:",$4}')
WIFI=$(nmcli device status | grep kapcsolódva | awk '{print $2}' || echo "none")
DATESTATUS=$(date +"%A %H:%M, %Y. %b. %d. %Z")
VOLUME=$(pamixer --get-volume-human | awk '{print "vol:" $0}')
BATTERY=$(acpi | awk '{print "B:" $4 " " $5}')
 echo "    $DISKUSAGE | $WIFI | $VOLUME | $BATTERY | $DATESTATUS | b:$BRIGHTNESS  "
#| awk -vORS="" '1'
